export default {
    pt: {
        id: "pt",
        title: "Português",
        dashboard:{
            title: "Dashboard"
        },
        configuracoes:{
            title: "Configurações",
            cabecalho: "Cabeçalho",
            lateralEsquerda: "Lateral esquerda",
            esquerdaIcons: "Lateral esquerda (Apenas icones)",
            lateralDireita: "Lateral direita",
            acima: "Acima",
            lateralEsquerdaDinamico: "Lateral esquerda dinâmico",
            idioma: "Idioma",
            corSistema: "Cor do sistema",
            lightMode: "Light Mode",
            darkMode: "Dark Mode",
            customizada: "Customizada",
        },
        sobre: {
            title: "Sobre o sistema",
            versionText: "Versão: ",
        },
        geral: {
            erroRecuperarInfo: "Não foi possível recuperar informações!",
            dscSistema: "Sistema: ",
            dscPerfil: "Perfil: ",
            dscEmpresa: "Empresa: ",
            dscLocalidade: "Localidade: ",
            dscHierarquia: "Hierarquia: ",
            dscAdicionar: "Adicionar",
            dscCancelar: "Cancelar",
        },
    },
    en: {
        id: "en",
        title: "English",
        dashboard:{
            title: "Dashboard"
        },
        configuracoes:{
            title: "Settings",
            cabecalho: "Header",
            lateralEsquerda: "Left side",
            esquerdaIcons: "Left side (only icons)",
            lateralDireita: "Right side",
            acima: "Top",
            lateralEsquerdaDinamico: "Dynamic left side",
            idioma: "Language",
            corSistema: "System color",
            lightMode: "Light Mode",
            darkMode: "Dark Mode",
            customizada: "Custom",
        },
        sobre: {
            title: "About system",
            versionText: "Version: ",
        },
        geral: {
            erroRecuperarInfo: "Couldn't retrieve information!",
            dscSistema: "System: ",
            dscPerfil: "Profile: ",
            dscEmpresa: "Company: ",
            dscLocalidade: "Locality: ",
            dscHierarquia: "Hierarchy: ",
            dscAdicionar: "Add",
            dscCancelar: "Cancel",
        },
    },
    es: {
        id: "es",
        title: "Español",
        dashboard:{
            title: "Dashboard"
        },
        configuracoes:{
            title: "Ajustes",
            cabecalho: "Encabezamiento",
            lateralEsquerda: "Lateral izquierdo",
            esquerdaIcons: "Lateral izquierdo (Apenas icones)",
            lateralDireita: "Lateral derecha",
            acima: "Arriba",
            lateralEsquerdaDinamico: "Lateral izquierdo dinámico",
            idioma: "Idioma",
            corSistema: "Color del sistema",
            lightMode: "Light Mode",
            darkMode: "Dark Mode",
            customizada: "Personalizado",
        },
        sobre: {
            title: "Sobre el sistema",
            versionText: "Versión: ",
        },
        geral: {
            erroRecuperarInfo: "¡No se pudo recuperar la información!",
            dscSistema: "Sistema: ",
            dscPerfil: "Perfil: ",
            dscEmpresa: "Empresa: ",
            dscLocalidade: "Localidad: ",
            dscHierarquia: "Jerarquía: ",
            dscAdicionar: "Finalizar",
            dscCancelar: "Cancelar",
        },
    },
};
